# Generated by Django 2.2.24 on 2022-02-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reqi_holy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sir', models.CharField(max_length=50)),
                ('typ_holy', models.CharField(max_length=20)),
                ('reson', models.CharField(max_length=50)),
                ('num_day', models.CharField(max_length=10)),
                ('date_start', models.CharField(max_length=15)),
                ('time1', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('order', models.CharField(max_length=50)),
                ('signing', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'جدول المعلمين',
            },
        ),
    ]
