# Generated by Django 2.2.24 on 2022-02-24 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqi_holy',
            name='agree',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='reqi_holy',
            name='time1',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
