# Generated by Django 2.2.24 on 2022-02-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpag', '0003_reqi_holy_see'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqi_holy',
            name='see',
            field=models.CharField(default='جديد', max_length=1),
        ),
    ]
