# Generated by Django 2.2.24 on 2022-06-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpag', '0004_auto_20220226_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqi_holy',
            name='see',
            field=models.CharField(default='جديد', max_length=5),
        ),
    ]
